# Generated by Django 3.0.1 on 2020-01-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
