# Generated by Django 3.0.2 on 2020-02-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200213_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='attributes',
            field=models.CharField(blank=True, default='No attribute', max_length=255),
        ),
    ]
