# Generated by Django 3.0.3 on 2020-05-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='completed_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
