# Generated by Django 3.0.3 on 2020-05-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_auto_20200513_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
