# Generated by Django 3.0.2 on 2020-02-21 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('liability', models.FloatField(default=0)),
                ('liability_limit', models.FloatField(default=0)),
                ('dob', models.DateField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('individualprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.IndividualProfile')),
            ],
            bases=('profiles.individualprofile',),
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('individualprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='profiles.IndividualProfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('profiles.individualprofile',),
        ),
    ]
