# Generated by Django 3.0.2 on 2020-02-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualprofile',
            name='position',
            field=models.CharField(default='Nhân Viên', max_length=50),
        ),
    ]
