# Generated by Django 3.0.3 on 2020-02-25 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_delete_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=60)),
                ('owner', models.CharField(max_length=50)),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='profiles.CustomerProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
