# Generated by Django 3.0.3 on 2020-02-25 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('profiles', '0005_auto_20200225_0258'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=60)),
                ('owner', models.CharField(max_length=50)),
                ('own', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='customers.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='individualcustomerbankaccount',
            name='customer_profile',
        ),
        migrations.RemoveField(
            model_name='companycustomerprofile',
            name='code',
        ),
        migrations.AddField(
            model_name='companycustomerprofile',
            name='own',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to='customers.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualcustomerprofile',
            name='own',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='individual_profile', to='customers.Customer'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompanyCustomerBankAccount',
        ),
        migrations.DeleteModel(
            name='IndividualCustomerBankAccount',
        ),
    ]
