# Generated by Django 3.0.3 on 2020-02-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_individualcustomerprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycustomerprofile',
            name='liability',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='companycustomerprofile',
            name='liability_limit',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='individualcustomerprofile',
            name='liability',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='individualcustomerprofile',
            name='liability_limit',
            field=models.FloatField(default=0, null=True),
        ),
    ]
