# Generated by Django 3.0.3 on 2020-03-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200226_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbankaccount',
            name='account_number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
