# Generated by Django 3.0.3 on 2020-05-13 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationShipType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserRelationShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_user', to=settings.AUTH_USER_MODEL)),
                ('relating_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relating_user', to=settings.AUTH_USER_MODEL)),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_type', to='users.RelationShipType')),
            ],
        ),
    ]
