# Generated by Django 3.0.1 on 2020-01-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200112_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permission',
            field=models.CharField(default='limited', max_length=50, null=True),
        ),
    ]
