# Generated by Django 3.0.2 on 2020-02-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200215_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission',
        ),
    ]
