# Generated by Django 3.0.2 on 2020-02-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_role_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permission',
        ),
    ]
