# Generated by Django 3.0.2 on 2020-02-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_role_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
